cnz:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DEV_PROJECT_ID') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 10
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('PROD_PROJECT_ID') }}"
      schema: prod
      threads: 10
      timeout_seconds: 300
      location: EU
      priority: interactive
      retries: 1
