name: dbt
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: pip install pipenv
      - run: pipenv sync --dev
      - run: pipenv run dbt -h
