name: dbt CI clean-up
on:
  schedule:
    - cron: '22 22 * * *'
env:
  DEV_PROJECT_ID: ${{ secrets.GCP_DATA_WAREHOUSE_DEV_PROJECT_ID }}
jobs:
  dbt_ci_clean_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_DATA_WAREHOUSE_SA_KEY }}
          export_default_credentials: true
      - run: ./scripts/dbt_ci_clean_up.sh
